async def create_auto_fix_pr(repo_full_name: str, pr_number: int, findings: list, github_client) -> str:
    """
    Creates an auto-fix Pull Request applying suggested fixes for HIGH and CRITICAL findings.
    
    Args:
        repo_full_name: Format 'owner/repo'
        pr_number: The PR number that triggered the auto-fix
        findings: List of Finding elements
        github_client: An instantiated asynchronous GitHub client
        
    Returns:
        The URL of the created fix Pull Request as a string, or None if no critical/high findings exist.
    """
    # Filter only CRITICAL and HIGH severity findings
    target_findings = [f for f in findings if f.severity in ["CRITICAL", "HIGH"]]
    
    # Return early if no relevant findings
    if not target_findings:
        return None
        
    branch_name = f"redflag/fix-{pr_number}"
    
    # Call create_branch with branch name "redflag/fix-{pr_number}"
    await github_client.create_branch(
        repository=repo_full_name,
        branch_name=branch_name
    )
    
    # For each finding, call github_client.commit_file with the fix from finding.fix
    for finding in target_findings:
        commit_message = f"Auto-fix ({finding.severity}): RedFlag CI fix applied for {finding.file} at line {finding.line}"
        await github_client.commit_file(
            repository=repo_full_name,
            file_path=finding.file,
            content=finding.fix, 
            message=commit_message,
            branch=branch_name
        )
        
    # Build PR description summarizing the applied fixes
    pr_body = (
        "This is an automated fix generated by **RedFlag CI**.\n\n"
        "### Security Findings Addressed:\n"
    )
    for f in target_findings:
        pr_body += f"- **{f.severity}** in `{f.file}:{f.line}` - {f.description}\n"
        
    # Call github_client.create_pull_request with specific title
    pr_title = f"RedFlag CI — Auto Fix for PR #{pr_number}"
    pull_request = await github_client.create_pull_request(
        repository=repo_full_name,
        title=pr_title,
        body=pr_body,
        head=branch_name,
        base="main"  # Targeting main by default; can be improved to use the original PR's base
    )
    
    # Return the created PR URL
    # Handle response regardless of if it's a dict or property model
    if hasattr(pull_request, 'html_url'):
        return pull_request.html_url
    if isinstance(pull_request, dict):
        return pull_request.get('html_url')
        
    return str(pull_request)
