"""
fingerprint.py — AI Code Fingerprinting Engine
Owner: Nikhil Virdi (NV)

Analyzes changed files in a PR and classifies them as 
AI-generated or human-written using heuristic signals.
AI-flagged files receive a stricter scan ruleset.
"""

import re
import logging

logger = logging.getLogger(__name__)


# ─── Heuristic Patterns ────────────────────────────────────
# These patterns indicate code generated by AI tools.

AI_COMMENT_PATTERNS = [
    # Copilot / Cursor markers
    r"(?i)generated\s+by\s+(copilot|cursor|claude|chatgpt|gpt|ai)",
    r"(?i)ai[\s-]*(suggested|generated|written|created|assisted)",
    r"(?i)GitHub\s+Copilot",
    r"(?i)auto[- ]?generated",
    # LLM conversational residue
    r"(?i)^(sure|certainly|of course)[,!]\s*(here|let me|i'?ll)",
    r"(?i)implementation\s+below",
    r"(?i)here'?s\s+(a|the|an)\s+(complete|full|working)",
    r"(?i)you\s+can\s+(use|try|modify)\s+this",
    # Boilerplate markers
    r"(?i)TODO:\s*(implement|add|fix|complete|update)\s+this",
    r"(?i)placeholder\s+(code|implementation|value)",
]

AI_FILENAMES = [
    ".cursorrules",
    ".cursorignore",
    ".copilot",
    ".github/copilot",
    "PROMPT.md",
    "INSTRUCTIONS.md",
]

# Large single-file additions are a strong signal of vibe-coding sessions
LARGE_FILE_THRESHOLD = 200  # lines


class AIFingerprinter:
    """Classifies files as AI-generated or human-written."""

    def analyze_files(self, files: list[dict]) -> list[dict]:
        """
        Accepts files from get_pr_diff(). 
        Returns a list of findings for files detected as AI-generated.
        Also annotates each file dict in-place with 'is_ai_generated': bool.
        """
        findings = []

        # Check for AI config files in the PR
        has_ai_config = any(
            any(ai_name in f.get("filename", "").lower() for ai_name in AI_FILENAMES)
            for f in files
        )

        for f in files:
            filename = f.get("filename", "")
            content = f.get("content", "")
            patch = f.get("patch", "")
            full_text = f"{content}\n{patch}"

            signals = []

            # Signal 1: AI config file present in the same PR
            if has_ai_config:
                signals.append("AI config file (.cursorrules or similar) found in PR")

            # Signal 2: Comment pattern matching
            for pattern in AI_COMMENT_PATTERNS:
                if re.search(pattern, full_text):
                    signals.append(f"AI comment pattern matched: {pattern[:40]}...")
                    break  # one match is enough

            # Signal 3: Large single-file addition
            added_lines = len([
                line for line in patch.split("\n")
                if line.startswith("+") and not line.startswith("+++")
            ])
            if added_lines > LARGE_FILE_THRESHOLD:
                signals.append(f"Large file addition: {added_lines} lines added in one commit")

            # Signal 4: Repetitive boilerplate structure
            if _has_boilerplate_repetition(content):
                signals.append("Repetitive boilerplate structure detected")

            # Classify
            is_ai = len(signals) >= 1
            f["is_ai_generated"] = is_ai

            if is_ai:
                findings.append({
                    "type": "AI_FINGERPRINT",
                    "severity": "LOW",
                    "file": filename,
                    "line": 0,
                    "description": (
                        f"File classified as AI-generated. Signals: {'; '.join(signals)}. "
                        "Applying enhanced security ruleset."
                    ),
                    "fix_code": "",
                })

        ai_count = sum(1 for f in files if f.get("is_ai_generated"))
        logger.info(
            "Fingerprinting complete: %d/%d files classified as AI-generated.",
            ai_count, len(files),
        )
        return findings


def _has_boilerplate_repetition(content: str) -> bool:
    """
    Detect repetitive structural patterns common in AI output,
    such as repeated try/except blocks, identical function signatures, etc.
    """
    lines = content.split("\n")
    if len(lines) < 20:
        return False

    # Check for high ratio of similar-length lines (AI tends to produce very uniform code)
    lengths = [len(line.strip()) for line in lines if line.strip()]
    if not lengths:
        return False

    from collections import Counter
    length_counts = Counter(lengths)
    most_common_count = length_counts.most_common(1)[0][1]

    # If > 40% of lines have the same length, likely boilerplate
    return most_common_count / len(lengths) > 0.4
