// Full v2 mock data matching the frozen API schema

export const MOCK_SCANS = [
  {
    pr_number: 42,
    vibe_risk_score: 87,
    ai_confidence_score: 92,
    code_reliability_score: 'LOW',
    timestamp: '2026-04-01T10:30:00Z',
    repo_name: 'acme/vibe-app',
    findings_summary: { critical: 3, high: 2, medium: 4, low: 1 },
  },
  {
    pr_number: 41,
    vibe_risk_score: 45,
    ai_confidence_score: 78,
    code_reliability_score: 'MEDIUM',
    timestamp: '2026-03-31T16:00:00Z',
    repo_name: 'acme/vibe-app',
    findings_summary: { critical: 1, high: 1, medium: 3, low: 2 },
  },
  {
    pr_number: 38,
    vibe_risk_score: 12,
    ai_confidence_score: 35,
    code_reliability_score: 'HIGH',
    timestamp: '2026-03-30T09:15:00Z',
    repo_name: 'acme/dashboard',
    findings_summary: { critical: 0, high: 0, medium: 1, low: 3 },
  },
  {
    pr_number: 36,
    vibe_risk_score: 68,
    ai_confidence_score: 85,
    code_reliability_score: 'LOW',
    timestamp: '2026-03-29T14:45:00Z',
    repo_name: 'acme/api-server',
    findings_summary: { critical: 2, high: 3, medium: 1, low: 0 },
  },
  {
    pr_number: 33,
    vibe_risk_score: 5,
    ai_confidence_score: 10,
    code_reliability_score: 'HIGH',
    timestamp: '2026-03-28T11:20:00Z',
    repo_name: 'acme/docs',
    findings_summary: { critical: 0, high: 0, medium: 0, low: 2 },
  },
];

export const MOCK_SCAN_DETAIL = {
  pr_number: 42,
  vibe_risk_score: 87,
  ai_confidence_score: 92,
  code_reliability_score: 'LOW',
  timestamp: '2026-04-01T10:30:00Z',
  bedrock_cost_usd: 0.0031,
  bedrock_cost_without_routing_usd: 0.0310,
  cost_savings_pct: 90,
  compliance_summary: {
    owasp_violations: ['A03:2021', 'A06:2021', 'A07:2021'],
    soc2_violations: ['CC6.1', 'CC6.6', 'CC6.7', 'CC7.1', 'CC8.1'],
    cis_violations: ['2.1', '13.1', '18.1'],
    waf_violations: [],
    llm_owasp_violations: ['LLM01:2025'],
    total_controls_violated: 12,
    audit_ready: false,
  },
  findings: [
    {
      type: 'SECRET',
      severity: 'CRITICAL',
      file: 'config/settings.py',
      line: 14,
      description: 'Hardcoded OpenAI API key detected: sk-proj-****',
      fix_code: 'api_key = os.getenv("OPENAI_API_KEY")',
      compliance_violations: ['SOC2:CC6.1', 'SOC2:CC6.7', 'OWASP:A07:2021'],
      audit_impact: 'Hardcoded credentials violate SOC 2 Type II access control requirements.',
      exploit_payload: {
        payload: "curl -H 'Authorization: Bearer sk-proj-LEAKED' https://api.openai.com/v1/models",
        impact: 'Attacker uses leaked key to make unauthorized API calls, incurring massive costs.',
        curl_example: "curl -H 'Authorization: Bearer sk-proj-LEAKED' https://api.openai.com/v1/chat/completions",
      },
      root_cause: {
        why_llm_generated_this: 'LLMs reproduce patterns from training data where API keys are hardcoded in example code.',
        llm_behavioral_pattern: 'Training data reproduction bias',
        developer_mistake: 'Accepted AI-generated code containing hardcoded credentials without security review',
        how_to_avoid: "Add to .cursorrules: 'Never hardcode API keys. Always use os.getenv().'",
      },
    },
    {
      type: 'SQL',
      severity: 'CRITICAL',
      file: 'routes/users.js',
      line: 28,
      description: 'SQL injection via string concatenation in user lookup query',
      fix_code: "db.query('SELECT * FROM users WHERE id = $1', [req.params.id])",
      compliance_violations: ['OWASP:A03:2021', 'SOC2:CC6.6'],
      audit_impact: 'SQL injection vulnerability violates OWASP A03:2021.',
      exploit_payload: {
        payload: "1' OR '1'='1' UNION SELECT username, password FROM users--",
        impact: 'Dumps all user credentials from the database.',
        curl_example: "curl 'https://api.example.com/users?id=1%27%20OR%20%271%27%3D%271%27--'",
      },
      root_cause: {
        why_llm_generated_this: 'LLMs choose string concatenation because it satisfies the requirement with fewest tokens.',
        llm_behavioral_pattern: 'Shortest-path optimization bias',
        developer_mistake: 'Trusted LLM output without verifying parameterization',
        how_to_avoid: "Add to .cursorrules: 'All SQL queries MUST use parameterized statements.'",
      },
    },
    {
      type: 'PACKAGE',
      severity: 'CRITICAL',
      file: 'package.json',
      line: 8,
      description: 'Hallucinated package `openai-stream-helper` does not exist in npm registry',
      fix_code: '// Remove openai-stream-helper and use the official openai package',
      compliance_violations: ['OWASP:A06:2021', 'SOC2:CC8.1'],
      audit_impact: 'Hallucinated dependencies violate OWASP A06:2021.',
      reputation: {
        trust_level: 'DANGEROUS',
        weekly_downloads: 0,
        package_age_days: 0,
        has_repository: false,
      },
      root_cause: {
        why_llm_generated_this: 'LLMs hallucinate package names by combining real fragments into plausible-sounding packages.',
        llm_behavioral_pattern: 'Name hallucination via fragment recombination',
        developer_mistake: 'Did not verify dependencies exist before installing',
        how_to_avoid: "Run 'npm view <package>' for every AI-suggested dependency.",
      },
    },
    {
      type: 'PROMPT',
      severity: 'HIGH',
      file: 'routes/chat.js',
      line: 15,
      description: 'User input passed directly to LLM API without sanitization — prompt injection vector',
      fix_code: 'const sanitized = sanitizeForLLM(req.body.message);\nmessages: [{ role: "user", content: sanitized }]',
      compliance_violations: ['OWASP:A03:2021', 'OWASP:LLM01:2025'],
      audit_impact: 'Prompt injection violates OWASP LLM01:2025.',
      root_cause: {
        why_llm_generated_this: 'LLMs generate the most direct integration path — passing request.body directly to messages.',
        llm_behavioral_pattern: 'Functionality-first generation bias',
        developer_mistake: 'Did not add input sanitization between user input and LLM API calls',
        how_to_avoid: "Add to .cursorrules: 'All user input to LLMs must pass through sanitize_for_llm().'",
      },
    },
    {
      type: 'GIT',
      severity: 'HIGH',
      file: 'config.js',
      line: 3,
      description: 'Stripe API key found in removed lines — still accessible in git history',
      fix_code: 'git filter-repo --invert-paths --path config.js\n# Then rotate the Stripe key immediately',
      compliance_violations: ['SOC2:CC6.7', 'OWASP:A07:2021'],
      audit_impact: 'Secrets in git history remain permanently accessible.',
      root_cause: {
        why_llm_generated_this: "LLMs don't understand git history persistence. They delete the line but the secret remains.",
        llm_behavioral_pattern: 'Stateless context assumption',
        developer_mistake: 'Assumed deleting removes the secret permanently.',
        how_to_avoid: 'After removing any secret: rotate immediately + use git-filter-repo to purge.',
      },
    },
    {
      type: 'LLM_ANTIPATTERN',
      severity: 'MEDIUM',
      file: 'server.js',
      line: 5,
      description: 'CORS wildcard configuration allows any origin to make requests',
      fix_code: "app.use(cors({ origin: ['https://myapp.com'] }))",
      compliance_violations: ['OWASP:A05:2021', 'SOC2:CC6.6'],
      audit_impact: 'CORS wildcard violates basic security configuration requirements.',
      root_cause: {
        why_llm_generated_this: 'LLMs use cors() with no config because it works immediately with zero configuration.',
        llm_behavioral_pattern: 'Permissive default bias',
        developer_mistake: 'Deployed AI-generated CORS configuration without restricting origins',
        how_to_avoid: "Add to .cursorrules: 'Never use cors() without explicit origin list.'",
      },
    },
    {
      type: 'IAC',
      severity: 'MEDIUM',
      file: 'terraform/s3.tf',
      line: 12,
      description: 'S3 bucket configured without BlockPublicAccess — data exposure risk',
      compliance_violations: ['SOC2:CC6.1', 'CIS:5.1'],
      audit_impact: 'Public S3 bucket violates SOC 2 access control requirements.',
    },
    {
      type: 'PIPELINE',
      severity: 'MEDIUM',
      file: '.github/workflows/deploy.yml',
      line: 7,
      description: 'GitHub Actions workflow uses unpinned third-party action versions',
      compliance_violations: ['SOC2:CC8.1', 'CIS:16.1'],
      audit_impact: 'Unpinned actions enable supply chain attacks.',
    },
    {
      type: 'LLM_ANTIPATTERN',
      severity: 'MEDIUM',
      file: 'routes/api.js',
      line: 22,
      description: 'Missing rate limiting on public API endpoints',
      compliance_violations: ['SOC2:CC6.6'],
      audit_impact: 'Missing rate limiting increases DDoS risk.',
    },
    {
      type: 'AI_FINGERPRINT',
      severity: 'LOW',
      file: '.cursorrules',
      line: 1,
      description: 'AI tool configuration file detected — PR contains AI-generated code',
    },
  ],
};

export const MOCK_CHART_DATA = [
  { pr: 'PR #33', security: 5, aiConfidence: 10, reliability: 95 },
  { pr: 'PR #36', security: 68, aiConfidence: 85, reliability: 40 },
  { pr: 'PR #38', security: 12, aiConfidence: 35, reliability: 90 },
  { pr: 'PR #41', security: 45, aiConfidence: 78, reliability: 55 },
  { pr: 'PR #42', security: 87, aiConfidence: 92, reliability: 25 },
];

export const MOCK_METRICS = {
  prsScanned: 142,
  secretsBlocked: 38,
  criticalFindings: 67,
  activeRepos: 12,
  costSavings: 90,
  complianceViolations: 45,
};
